site_name: DBNOSTIX
dev_addr: "127.0.0.1:8003"

theme:
  name: material
  logo: images/blue_butterfly.png
  custom_dir: overrides  # Enables Bootstrap customization
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: blue
    accent: deep-orange
  features:
    - content.code.copy  # Enables copy button for code blocks
    - content.code.annotate  # Allows annotations in code blocks
    - content.tabs.link  # Enables linked tabs
    - navigation.expand  # Expands sidebar navigation by default
    - navigation.instant  # Instant page loading
    - navigation.sections  # Allows section grouping
    - navigation.tabs # Allows navbar tabs  
    - toc.follow  # Keeps TOC visible
    - content.tooltips  # Enables tooltips on hover
    - content.code.highlight  # Enables syntax highlighting
    - content.grid  # Enables grid system for cards
     

use_directory_urls: False

extra_css:
  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css
  - https://cdn.jsdelivr.net/npm/bootswatch@5.3.3/dist/cerulean/bootstrap.min.css
  - stylesheets/extra.css

markdown_extensions:
  - admonition  # Enables "Note", "Tip", "Warning" blocks
  - pymdownx.details  # Collapsible details blocks
  - pymdownx.superfences  # Allows nesting of code blocks and tabs
  - pymdownx.tabbed:
      alternate_style: true  # Enables tabbed content~
  - pymdownx.snippets  # Allows including external Markdown files
  - attr_list  # Allows attributes lik  # features:  
  - md_in_html  # Allows Markdown inside HTML blocks


nav:
  - Dbnostix: 
      - index.md
      - dbnostix/projects.md     
      - dbnostix/contact.md
      - dbnostix/services.md
      - dbnostix/help.md      
  - Services:
      - services/database_infrastructure.md
      - services/data_science.md
      - services/predictive_modeling.md
      - services/large_language_model.md
  - Python:
      - python/00_landing.md     
      - python/00_Contents.md 
      - python/00_Contents_Jazzy.md 
      - python/01_Overview.md
      - python/02_Setup_Installation.md
      - python/03_Core_Concepts.md     
      - python/04_Advanced_Concepts.md
      - python/05_Syntax_and_Variables.md
      - python/06_Control_Flow.md
      - python/07_Data_Structures.md
      - python/08_Functions_and_Modules.md
      - python/09_Object-Oriented_Programming.md
      - python/10_Python_Standard_Library.md
      - python/11_File_Handling_and_IO.md      
      - python/12_Exception_Handling_and_Debugging.md
      - python/13_Web_Development.md
      - python/14_Data_Science.md
      - python/15_Machine_Learning_and_AI.md     
      - python/16_Predictive_Modeling.md
      - python/17_Databases.md
      - python/17x_Examples.md                                 
      - python/pandas.md
      - python/yfinance.md
      - python/best_practice.md
      - python/f_strings.md
      - python/list_function.md
  - Pandas:
      - pandas/contents.md
      - pandas/select_filter.md
      - pandas/generate_data.md
      - pandas/cheat_sheet.md
      - pandas/list_function.md
      - pandas/quick_examples.md
      - pandas/numpy.md
      - pandas/skimpy.md
      - pandas/summarizer.md
      - pandas/profiling.md
      - pandas/google_sheets.md
      - pandas/advanced_techniques.md
      - pandas/dataframe_creation.md
      - pandas/dataframe_tips.md
      - pandas/etl.md                  
  - AlgoTrade:
      - algotrade/algotrade.md
      - algotrade/extract.md
      - algotrade/transform.md
      - algotrade/load.md      
  - Options:
      - options/contents.md
      - options/strangle_strategy.md
  - GPT:
      - gpt/00_gpt.md
      - gpt/01_llm_mcp.md
      - gpt/20_mcp_ollama_build.md
      - gpt/20_mcp_server_build.md
  - Cloud:
      - cloud/oracle_cloud.md
  - Database:
      - database/database.md
      - database/db2.md
      - database/postgresql.md
      - database/duckdb.md
      - database/duckdb_motherduck.md
      - database/duckdb_intro.md
  - MkDocs: 
      - mkdocs/mkdocs.md
      - mkdocs/admonitions.md
      - mkdocs/collapsible_sections.md
      - mkdocs/emoji_guide.md
  
