site_name: DBNOSTIX

theme:
  name: material
  custom_dir: overrides  # Enables Bootstrap customization
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: blue
    accent: deep-orange
  features:
    - content.code.copy  # Enables copy button for code blocks
    - content.code.annotate  # Allows annotations in code blocks
    - content.tabs.link  # Enables linked tabs
    - navigation.expand  # Expands sidebar navigation by default
    - navigation.instant  # Instant page loading
    - navigation.sections  # Allows section grouping
    - navigation.tabs # Allows navbar tabs  
    - toc.follow  # Keeps TOC visible
    - content.tooltips  # Enables tooltips on hover
    - content.code.highlight  # Enables syntax highlighting
    - content.grid  # Enables grid system for cards
     

use_directory_urls: False

extra_css:
  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css
  - stylesheets/extra.css

markdown_extensions:
  - admonition  # Enables "Note", "Tip", "Warning" blocks
  - pymdownx.details  # Collapsible details blocks
  - pymdownx.superfences  # Allows nesting of code blocks and tabs
  - pymdownx.tabbed:
      alternate_style: true  # Enables tabbed content
  - pymdownx.snippets  # Allows including external Markdown files
  - attr_list  # Allows attributes lik  # features:  
  - md_in_html  # Allows Markdown inside HTML blocks


nav:
  - Dbnostix: 
      - index.md
      - dbnostix/company.md
      - dbnostix/about.md
      - dbnostix/contact.md
      - dbnostix/services.md
  - Services:
      - services/database_infrastructure.md
      - services/data_science.md
      - services/predictive_modeling.md
      - services/large_language_model.md
  - Python:
      - python/overview.md
      - python/pandas.md
      - python/yfinance.md
      - python/best_practice.md
  - AlgoTrade:
      - algotrade/algotrade.md
      - algotrade/extract.md
      - algotrade/transform.md
      - algotrade/load.md
  - Database:
      - database/database.md
      - database/db2.md
      - database/postgresql.md
      - database/duckdb.md
  - MkDocs: 
      - mkdocs/mkdocs.md
      - mkdocs/collapsible_sections.md
  - Obsidian:
      - obsidian/obsidian.md
      - obsidian/cards.md

